# Generated by Django 2.2.15 on 2021-03-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=64)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=64)),
                ('email_port', models.IntegerField(default=587)),
                ('Tls_value', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=264)),
                ('Ssl_value', models.BooleanField(default=False)),
            ],
        ),
    ]
